-- This query calculates the total revenue generated by each physician in the PHYSICIANS table:

SELECT ph.name, SUM(inv.instruction_fee + inv.room_fee) AS total_revenue FROM PHYSICIANS ph
JOIN MONITORED m ON ph.physician_id = m.physician_id
JOIN PATIENTS p ON m.patient_id = p.patient_id
JOIN INVOICES inv ON p.patient_id = inv.patient_id
GROUP BY ph.name;

 